version: '3'

services:

  myapp-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=todolist
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
    ports:
      - 3306:33061

  myapp-main:
    image: 964196a4ad27
    restart: on-failure
    networks:
      - spring-boot-mysql-network
    depends_on:
      - myapp-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_USER=user
      - DATABASE_PASSWORD=secret
      - DATABASE_NAME=todolist
      - DATABASE_PORT=33061

networks:
  spring-boot-mysql-network:
    driver: bridge